### ISSUE TITLE
Setup bootstrap and reorganize repositories

### ISSUE THREAD

**Issue by hemker** [pilsbot/pilsbot#26]

**Comment by PimpMyPizza** [comment]
For the moment, you can download the repositories directly with `pilsbot update`. See the README in https://github.com/pilsbot/workspace . There is no skript for installing the deps atm and the scripts are rudimentary and only tested in ubuntu.

**Comment by PimpMyPizza** [comment]
Maybe we should remove the `pilsbot_` prefix in the packages names

**Comment by DarthBubi** [comment]
Why should we drop that? It is common practice to prefix your device-specific packages.

**Comment by PimpMyPizza** [comment]
Okay, I just though that since all the packages are in the pilsbot group, the `pilsbot_` prefix was a little bit too much, but if that's a common practice, forget what I wrote. It would be cool if we use this for the related packages (some doesn't have the prefix even if they should, some have just `pils_` etc.

**Comment by Cirromulus** [comment]
Lul

**Comment by Cirromulus** [comment]
at least working demo is found under this example  workspace: [pilsbot/workspace](https://github.com/pilsbot/workspace)
